### ISSUE TITLE
Man NPC not attacking back after being killed once

### ISSUE THREAD

**Issue by Blunty19** [Tomm0017/rsmod#100]
## Current Behavior
After killing MAN_3080 he wont attack you back on his following spawns.
## Expected Behavior
The man should be able to attack back
## Steps to Reproduce the Problem

  1. Go and kill the man in edge
  2.once he has died wait for him to respawn
  3.attack him again and he doesn't attack back

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/330401693b88ca91449a8b83954757439d32a9f8
