### ISSUE TITLE
A second set of doors spawn.

### ISSUE THREAD

**Issue by Blunty19** [Tomm0017/rsmod#101]
## Current Behavior
When the doors in Edgeville (the building with the men inside) are left open and you leave the area another set of doors spawn. You can walk through these doors and once you close the original doors they disappear. This also happens with some gates, these being the cow and chicken farms on the east side of Lumbridge. I have not really explored past this so cant tell you if the issue exists on any others.
## Expected Behavior
Doors should either stay open or automatically close after x amount of time.
## Steps to Reproduce the Problem

  1. Open the double doors in Edge in the building where the men are. (as mentioned above this can also be done with gates)
  2. Teleport away (i used the Varrock Teleport)
  3. Return to Edge (i used the ::home command) and there will be 2 sets of doors

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/4a25c66c88043b004159c08bea532dd9e2f05653
