### ISSUE TITLE
Issue when spawning items above ground floor

### ISSUE THREAD

**Issue by Blunty19** [Tomm0017/rsmod#102]
## Current Behavior
When trying to spawn an item on a height above 0 it spawn on the ground floor and im unable to pick up the item.
## Expected Behavior
Item spawns on 1st floor and is able to be picked up.
## Steps to Reproduce the Problem

  1. add the following:

//Spawn knife upstairs
spawn_item(item = Items.KNIFE, amount = 1, x = 3218, z = 3418, height = 1)

//Spawn Spade upstairs
spawn_item(item= Items.SPADE, amount = 1, x = 3218, z = 3412, height = 1)
 
 2. Go to Varrock General store and see the items spawned on the ground floor.

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/a359791dc03bec94a7cd11b896b4add5da5ee3a3
