### ISSUE TITLE
filterableMessage

### ISSUE THREAD

**Issue by JackRayFish** [Tomm0017/rsmod#103]
## Current Behavior
When chopping down a tree, the filterableMessage e.g: `
                p.filterableMessage("You get some ${logName.toLowerCase()}.")`
does not appear in the chat box, changing chat tab and then changing back to main displays the message. This is with filter off.

## Expected Behavior
Message should be visible in main when filter is disabled.

## Steps to Reproduce the Problem

  1. Chop down a tree, get a log.
  2. Change main chat tab to another tab and back again.
  3. Message is now displayed.

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/7e34858b0e0354a5db702c06bcd5274cf5adaf8f
