### ISSUE TITLE
Bankers change direction after interacting with them.

### ISSUE THREAD

**Issue by Blunty19** [Tomm0017/rsmod#104]
## Current Behavior
After talking to or banking with a banker (also happens with grand exchange clerks) they will stay fixed on you and will change direction to where ever you move to.
## Expected Behavior
Bankers stay fixed in one direction in OSRS
## Steps to Reproduce the Problem

  1.Talk to or Bank with a Banker NPC
  2.Walk in any direction that the Banker is not meant to face
  3.The Banker will now be facing the wrong direction

**Comment by Tomm0017** [comment]
Issue isn't accurate
