### ISSUE TITLE
Accept trade via chatbox notification

### ISSUE THREAD

**Issue by Vashmeed** [Tomm0017/rsmod#116]
## Current Behavior
Does not open trade interface

## Expected Behavior
Open trade

## Steps to Reproduce the Problem

  1. Player 1: Send trade request
  2. Player 2: Attempt to accept trade request by clicking on trade chat notification

**Comment by YasinY** [comment]
This is not related to the server files, is it? I can't realise a way to detect the clicks on a trade notification server sided -> even if one would exist, it's inefficient as it could be done client sided (solely)

Correct me if I'm wrong:
Trading is a right click option, sent from the client

Player 1 right clicks Player 2 and sends a packet to the Server
-> Server receives the packet and finds Player 2 (lets ignore the pre-conditions for the trade request to send)

Now Player 2 has two possibilities in accepting:
- Right click -> Trade to accept
- Click on the chatbox to accept

How should the server know you're clicking on the chatbox to accept? Exactly! By sending the same packet you'd send when right click -> trade accepting. Client sided.

**Comment by ushort** [comment]
@YasinY well i dont know much about osrs or how trade works in general but its quite possible that after clicking accept itll send packet to server to let the server know trade was accepted which is obviously important and while it does that it opens up interface server sided. in fact i feel like thats very likely

**Comment by YasinY** [comment]
Yes, and that's what I ment! It'll simply send the identical packet to the server as if you'd have right-click traded. 
So this is pretty much out of the range of the server, the server doesn't need to know that the player has clicked the chatbox to accept the trade. Therefore this feature is not "needed" - as it's essentially a client-sided job

**Comment by Vashmeed** [comment]
It

> 
> 
> Yes, and that's what I ment! It'll simply send the identical packet to the server as if you'd have right-click traded.
> So this is pretty much out of the range of the server, the server doesn't need to know that the player has clicked the chatbox to accept the trade. Therefore this feature is not "needed" - as it's essentially a client-sided job

It's not client sided. Nothing should ever need to be changed on the client past getting it connected to the server. The server is not sending the player name on chatbox trade request acceptance.

**Comment by Vashmeed** [comment]
Solved in #119
