### ISSUE TITLE
Attack Option in Wilderness

### ISSUE THREAD

**Issue by DaGreenRs** [Tomm0017/rsmod#122]
## Current Behavior
Players cannot attack each other in Wilderness, because there is currently no attack option in the Wilderness.
## Expected Behavior
When player enters Wilderness, they should have `Attack` option.
## Steps to Reproduce the Problem
  1. Make an alt account
  2. Enter Wilderness with an alt account.

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/37609153adca0b20ebfc443ecc8278633819f89f
