### ISSUE TITLE
Change lastFacingDirection to a public var

### ISSUE THREAD

**Issue by Zerotica** [Tomm0017/rsmod#126]
## Current Behavior
lastFacingDirection is currently internal and cannot be accessed by plugins.
## Expected Behavior
lastFacingDirection should be publicly readable and set internally.
## Fix
@gg.rsmod.game.model.entity.Pawn.kt line ~83
var lastFacingDirection: Direction = Direction.SOUTH
    internal set

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/f448094118c173ec0d7d7edfbf3d438098190890
