### ISSUE TITLE
Woodcutting

### ISSUE THREAD

**Issue by sorasco** [Tomm0017/rsmod#130]
## Current Behavior
xp is being given after tree has been cut.

## Expected Behavior
xp is suppose to be given per log.
## Steps to Reproduce the Problem

  1. spawn a axe
  2. go woodcut any where
  3. cut the tree and xp will drop after the tree has depleted. (https://gyazo.com/c95d88345abf5d142f5031c3936b4c53) this should happen

**Comment by Tomm0017** [comment]
From internal testing, this seems to work fine. I assume there's an issue on your end. https://i.imgur.com/mO6hrJk.gifv
