### ISSUE TITLE
Be able to instance objects in static areas

### ISSUE THREAD

**Issue by Vashmeed** [Tomm0017/rsmod#133]
## Current Behavior
Unable to modify/create instanced objects in static regions.

## Expected Behavior
Be able to spawn instanced objects in static regions with multiple players.
Example: 
cox chest - has a purple light that is specific to the player it belongs to even though there are other players in the same region
abyss runecrafting - players enter one area and see each other but the objects mined/chopped/etc are randomized on entry and are specific to each player

**Comment by Tomm0017** [comment]
After some discussion, we decided it's best to stick with `multiloc` in [ObjectDef](https://github.com/Tomm0017/rsmod/blob/master/game/src/main/kotlin/gg/rsmod/game/fs/def/ObjectDef.kt#L104-L124)
