### ISSUE TITLE
Need to add inputString for chatbox dialogs

### ISSUE THREAD

**Issue by kyle-escobar** [Tomm0017/rsmod#141]
There is no feature for inputStrings()

The only that exist are inputInt().

**Comment by kyle-escobar** [comment]
I added the following code in the QueueTaskExt.kt class.
``/**
 * Prompts the player with an input dialog where they can enter text.
 * @return
 * The text as a String
 */
suspend fun QueueTask.inputString(description: String = "Enter text"): String {
    player.runClientScript(110, description)
    terminateAction = closeInput
    waitReturnValue()
    terminateAction!!(this)

    return requestReturnValue as? String ?: ""
}``

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/bdcf4bf3d9f3be8332d6f1da85679303f2ba434f
