### ISSUE TITLE
Add xprate multiplier to addXp method

### ISSUE THREAD

**Issue by LethalLeonard** [Tomm0017/rsmod#15]
Where it has xp in this method, change it to (xp * xpRate)
https://github.com/Tomm0017/rsmod/blob/dd500a63b6e6ab3aad825f6f4acc062878190234/game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt#L415

**Comment by Tomm0017** [comment]
Fixed in https://github.com/Tomm0017/rsmod/commit/d52198a2a2e6d5db7bccc6062adf3f273a98d3eb
