### ISSUE TITLE
Special attacks

### ISSUE THREAD

**Issue by jamili1** [Tomm0017/rsmod#150]
Please add a special attack handler so we can use it as a precedent. Thanks.

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/fb12f5fa97ef3b5ca6d2f5ddddcab2261d8ff251

Example: https://github.com/Tomm0017/rsmod/commit/930c9a42c7f687a0afe30c5d548e3c393d341583
