### ISSUE TITLE
Interface 187 options menu support

### ISSUE THREAD

**Issue by kyle-escobar** [Tomm0017/rsmod#152]
## Current Behavior
WaitReturnValue() never unsuspends since requetReturnValue is null until the interface is closed

suspend fun QueueTask.optionsMenu(vararg options: String, title: String = "Select an Option"): Int {
    player.sendTempVarbit(5983,1)
    player.runClientScript(2524, -1, -1)
    player.openInterface(187, InterfaceDestination.MAIN_SCREEN)
    player.runClientScript(217, title, options.joinToString("|"))
    player.setInterfaceEvents(interfaceId = 187, component = 3, range = 0..127, setting = 1)

    terminateAction = closeMenu
    waitReturnValue()
// waitReturnValue() never fires.
    terminateAction!!(this)

    return (requestReturnValue as? ResumePauseButtonMessage)?.slot ?: -1
}

**Comment by Tomm0017** [comment]
This is your own code. You should make an issue where you suggest adding this type of menu (showing a picture of how it's supposed to look) or make an issue on code that exists in the repository.
