### ISSUE TITLE
Add method to stun player

### ISSUE THREAD

**Issue by LethalLeonard** [Tomm0017/rsmod#16]
There should be a method to stun the player as in freeze them to a location and set a flag on the player that can be checked to see if they are stunned before doing an action. Useful for thieving, and weapon special attacks amongst other things.

**Comment by Tomm0017** [comment]
Is there a specific message you get when trying to move while _stunned_? Is it the same message that appears while frozen, "A magical force stops you from moving."?

**Comment by LethalLeonard** [comment]
Not in OSRS, you're just locked in place and can not move or interact with anything but I do believe you can eat when stunned or else I'd just use player.lock() and unlock()

**Comment by Tomm0017** [comment]
Fixed in https://github.com/Tomm0017/rsmod/commit/982726fef658b714233effa0f7ea19baea82e7f5
