### ISSUE TITLE
Process 'command' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by iisayboom** [Tomm0017/rsmod#183]
## Current Behavior
Execution failed for task ':game:run'.
> Process 'command '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

## Expected Behavior
Server starts

## Steps to Reproduce the Problem
I have followed all steps of the github page. Install goes fine but when starting the server I always run into that issue...
- I am on MacOS
- using IntelliJ 2019 ultimate
- Got openjdk 8 and 11 installed (both give same error, only version changes ofc)

**Comment by TSingularityR** [comment]
Fix?

**Comment by zpm346** [comment]
Old post, but it seems that this happens when RSMod doesn't support the cache you're using. It failed when I tried a 202, worked fine on a 181 (which was close to when this last was updated).
