### ISSUE TITLE
Combat XP greater than damage hit granted.

### ISSUE THREAD

**Issue by LethalLeonard** [Tomm0017/rsmod#22]
If you roll a higher hit than an NPC (and presumably player, though not tested) has, it grants xp for the damage that was rolled, and not the damage that was hit.  

Example:
an NPC has 8 hp left and you roll a 10, you get xp for the 10 damage even though you only hit an 8

**Comment by Tomm0017** [comment]
@LethalLeonard Are you saying it currently gives you XP for a damage of 10 on an npc with 8 hp, or that it should

**Comment by LethalLeonard** [comment]
So I attacked an enemy with 1hp left, and I got the experience of hitting a 3 when it did the 1hp in damage. It should give the experience of hitting a 1.

**Comment by Tomm0017** [comment]
Fixed in https://github.com/Tomm0017/rsmod/commit/201e9c06b8132af88ed4e045d59e3901b081bb6f
