### ISSUE TITLE
Stop action when player equips item/eats a food

### ISSUE THREAD

**Issue by war93** [Tomm0017/rsmod#24]
Just an example when player attacks an NPC
https://i.gyazo.com/f6fdde1a972b9efbbf4d71946adbc372.mp4

**Comment by Tomm0017** [comment]
So this seems to just reset the combat target which can be done. Is this logic also applied when eating food? (combat is reset when you eat food or drink potions?)

**Comment by war93** [comment]
> 
> 
> This seems to just reset the combat target, which can be done. Is this logic also applied when eating food? (combat is reset when you eat food or drink potions?)

Yeah, just tested it out on OSRS - Equipping item, eating food, drinking potions & dropping items resets the combat target

**Comment by Tomm0017** [comment]
Fixed in https://github.com/Tomm0017/rsmod/commit/08b2c7bc998bffadefc0f448f5af20d9fca671cf
