### ISSUE TITLE
Packet 28: Music Packet

### ISSUE THREAD

**Issue by lanternweb** [Tomm0017/rsmod#31]
Create regional music system and implement the packet

**Comment by Tomm0017** [comment]
Music packet has been added in commit https://github.com/Tomm0017/rsmod/commit/b998449cbfb3effe0d417aed83a54cae4e87584e & https://github.com/Tomm0017/rsmod/commit/b343820fba1bddae1b481557cae7554afc92de1a. If you wish for a regional music system, please create another issue and try to create one issue per feature.

**Comment by lanternweb** [comment]
> Music packet has been added in commit [b998449](https://github.com/Tomm0017/rsmod/commit/b998449cbfb3effe0d417aed83a54cae4e87584e) & [b343820](https://github.com/Tomm0017/rsmod/commit/b343820fba1bddae1b481557cae7554afc92de1a). If you wish for a regional music system, please create another issue and in the future try to create one issue per feature.

Thank-you, in future I will.
