### ISSUE TITLE
Regional Music System

### ISSUE THREAD

**Issue by lanternweb** [Tomm0017/rsmod#36]
Implement a music system which plays tracks based on which region the player is standing in. I'll write all the data.

**Comment by TristonPlummer** [comment]
What kind of system are you looking for? A bit more detail would be nice. If you're just after something that plays music upon entering a region, you can do the following:

```kotlin
enum class RegionalSongs(val region: Int, val song: Int) {
    LUMBRIDGE(region = 12850, song = 123);

    companion object {
        val values = enumValues<RegionalSongs>()
    }
}

RegionalSongs.values.forEach { regionalSong ->
    on_enter_region(regionId = regionalSong.region) { player.playSong(regionalSong.song) }
}
```

**Comment by Tomm0017** [comment]
Closed due to inactivity
