### ISSUE TITLE
kill an npc with ranged weapon

### ISSUE THREAD

**Issue by kyansh** [Tomm0017/rsmod#62]
## Expected Behavior
when you kill any npc it should die and respawn normally without any problems

## Actual Behavior
when you kill the npc with range , the npc will not die and u cant attack it again

## Steps to Reproduce the Problem

  1.wear ranged weapon with arrows
  2.kill any npc
  3.

here is the error when u kill npc with range 
https://pastebin.com/AJNvadmM

**Comment by Tomm0017** [comment]
The issue occurrs when a newly created character tried to drop an item. Will be fixing shortly.
