### ISSUE TITLE
Add player on player menu options

### ISSUE THREAD

**Issue by LethalLeonard** [Tomm0017/rsmod#67]
## Expected Behavior
A list of options based on where the players are and actions players can do on each other.
https://i.imgur.com/wdcpmll.png this would include "attack" in the wilderness.

## Actual Behavior
Currently just a "walk here" option. 
https://i.imgur.com/pWFTfFE.png

## Steps to Reproduce the Problem

  1. Right-click another player entity

**Comment by Tomm0017** [comment]
Added in https://github.com/Tomm0017/rsmod/commit/d778ff9d3d706a685d847d66cd55d370eeeea1b1 and https://github.com/Tomm0017/rsmod/commit/e7fd05578d8c4206808ba055ae2dc22cc77ab1b5
