### ISSUE TITLE
Don't use javadoc/kdoc documentation style where it is not applicable.

### ISSUE THREAD

**Issue by notmeta** [Tomm0017/rsmod#69]
Example: https://github.com/Tomm0017/rsmod/blob/master/game/plugins/src/main/kotlin/gg/rsmod/plugins/content/osrs.kts

Javadoc/KDoc is used to document methods, classes, members etc. rather than as casual comments explaining some code.

https://kotlinlang.org/docs/reference/kotlin-doc.html#kdoc-syntax

**Comment by Tomm0017** [comment]
Fixed in https://github.com/Tomm0017/rsmod/commit/2fb34b567744bb6a60cb3c7318285da66146d6e6
