### ISSUE TITLE
when you die for npc

### ISSUE THREAD

**Issue by kyansh** [Tomm0017/rsmod#71]
## Expected Behavior
if player dies to an npc and u back to fight the same npc , both will fight

## Actual Behavior
if the player dies to an npc and that player back to fight the same npc , the npc will not fight just the player

## Steps to Reproduce the Problem

  1.fight npc 
  2.die to that npc 
  3.fight the same npc again

**Comment by Tomm0017** [comment]
Fixed in https://github.com/Tomm0017/rsmod/commit/2e83af030f9aa1dafd109f11b2e78583e593d5ec
