### ISSUE TITLE
Non-combat NPCs can be attacked

### ISSUE THREAD

**Issue by HolyRSPS** [Tomm0017/rsmod#74]
## Expected Behavior
Non-combat NPCs such as Bankers, Shop keepers shouldn't be able to be attacked with magic.

## Actual Behavior
If you cast a magic spell to any NPC, it hits them and they won't respawn.

**Comment by Tomm0017** [comment]
Fixed in https://github.com/Tomm0017/rsmod/commit/461f3e91ce4108d509f5cd20ac54be008d97c979
