### ISSUE TITLE
Make-Over Mage & Thessalia NPC

### ISSUE THREAD

**Issue by Porazdir** [Tomm0017/rsmod#88]
## Expected Behavior
Thessalia to change between Male / Female, Charcter apperance, All skin colour with the additional green, white, black & zombie blue

## Actual Behavior
As of now their is a default charcter setup and are unable to change it.

## Steps to Reproduce the Problem

  1. 
  2. 
  3.

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/f8c69d7bdbaf04fdec10e87f058d99a217a70d3b

**Comment by Porazdir** [comment]
Doesn't save when logging out and will resort back to default appearance when you log back in or change player privilege.

as shown: https://gyazo.com/4bc0fa1efd9791aa5fc46e541c8f5069
