### ISSUE TITLE
Ctrl + click on tile lets you run without using run energy

### ISSUE THREAD

**Issue by LethalLeonard** [Tomm0017/rsmod#89]
## Expected Behavior
If you hold control and click on a tile, your character runs to it with using run energy.

## Actual Behavior
If you hold control and click on a tile, your character runs to it. But, if you have run turned off it does not use run energy.

## Steps to Reproduce the Problem

  1. Turn off run energy
  2. Hold control and click on a tile

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/d408dd42c110a729ffa92305063a2957b3da6461
