### ISSUE TITLE
Make logger static

### ISSUE THREAD

**Issue by Bartvhelvert** [Tomm0017/rsmod#9]
According to kotlin logging utlity docs this is the preffered way of getting a logger: https://github.com/MicroUtils/kotlin-logging/wiki#obtaining-a-logger

**Comment by Tomm0017** [comment]
Removed the usage of KLogging()

**Comment by Tomm0017** [comment]
Fixed in https://github.com/Tomm0017/rsmod/commit/21d5fa429c5f231f09ed8ca0c537e18e31460fec
