### ISSUE TITLE
Players in area of new player get disconnected on chat message

### ISSUE THREAD

**Issue by LethalLeonard** [Tomm0017/rsmod#90]
## Expected Behavior
When a player talks, the game doesn't crash or disconnect players. 

## Actual Behavior
When a player enters the game for the first time and sends a chat message all players, including themselves, get forcefully disconnected from the server with the following message in console.
`Error: class242:278 client:1420 client:2913 client:2523 class52:381 class52:613 java.lang.Thread.run | java.lang.NullPointerException | 79,33,79,779,3087,3497,-64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
`
Though if you promote the player to a rank that has an icon, the new user does not disconnect other players.

## Steps to Reproduce the Problem

  1. Create a new account and log into the server
  2. Send a message
  3. Get disconnected

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/6a7b59f1f744a32a52ad46495a7e39ef86f21956
