### ISSUE TITLE
Home teleport in combat

### ISSUE THREAD

**Issue by HolyRSPS** [Tomm0017/rsmod#93]
## Expected Behavior
Player should not be able to cast home teleport while in combat.

## Actual Behavior
In combat, player can cast home teleport and it will not stop the action even if player gets hit.

## Steps to Reproduce the Problem

  1. Attack an npc or player
  2. Cast home teleport

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/6a7b59f1f744a32a52ad46495a7e39ef86f21956

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/1fa7793a78bf1ce387f5d0392b461495851bbcd1
