### ISSUE TITLE
Examine item in equipment tab unequips

### ISSUE THREAD

**Issue by LethalLeonard** [Tomm0017/rsmod#94]
## Expected Behavior
When clicking examine, it examines the item

## Actual Behavior
When you click to examine, it unequips the item in the inventory area's equipment tab

## Steps to Reproduce the Problem

  1. equip an item
  2. switch to equipment tab
  3. examine the item

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/f6564168037f160e687c4fd77785d922f416b7c6
