### ISSUE TITLE
LockState bug

### ISSUE THREAD

**Issue by Johan24** [Tomm0017/rsmod#96]
## Current Behavior
When you thieve an NPC you are supposed to go into a LockState. However in this LockState you are able to pickup grounditems and if you do pick up an item during an attempted thieve your account will be glitched.

## Expected Behavior
Not allow picking up items during lockstate?
## Steps to Reproduce the Problem

  1. Drop an item
  2. Thieve npc
  3. Pick up item before the thieve is finished

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/bd77898a2fdcd3b401559f65a6b8acf50b7dfe90
